version: 0.2

phases:
  build:
    commands:
      - echo "Build commands go here"

artifacts:
  files: 
    - 'server/**/*'
  name: MyArtifact-${CODEBUILD_RESOLVED_SOURCE_VERSION}-${CODEBUILD_START_TIME}
cache:
  paths:
    - flask_upload/
