spring:
  config:
    import:
      - app.yml
  datasource:
    url: jdbc:mariadb://localhost:3306/travelsync
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: 1592

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
logging:
  level:
    root: info